require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comment_votes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CommentVote. As you add validations to CommentVote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CommentVote.create! valid_attributes
      get comment_votes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      comment_vote = CommentVote.create! valid_attributes
      get comment_vote_url(comment_vote)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_comment_vote_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      comment_vote = CommentVote.create! valid_attributes
      get edit_comment_vote_url(comment_vote)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CommentVote" do
        expect {
          post comment_votes_url, params: { comment_vote: valid_attributes }
        }.to change(CommentVote, :count).by(1)
      end

      it "redirects to the created comment_vote" do
        post comment_votes_url, params: { comment_vote: valid_attributes }
        expect(response).to redirect_to(comment_vote_url(CommentVote.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CommentVote" do
        expect {
          post comment_votes_url, params: { comment_vote: invalid_attributes }
        }.to change(CommentVote, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post comment_votes_url, params: { comment_vote: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested comment_vote" do
        comment_vote = CommentVote.create! valid_attributes
        patch comment_vote_url(comment_vote), params: { comment_vote: new_attributes }
        comment_vote.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the comment_vote" do
        comment_vote = CommentVote.create! valid_attributes
        patch comment_vote_url(comment_vote), params: { comment_vote: new_attributes }
        comment_vote.reload
        expect(response).to redirect_to(comment_vote_url(comment_vote))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        comment_vote = CommentVote.create! valid_attributes
        patch comment_vote_url(comment_vote), params: { comment_vote: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested comment_vote" do
      comment_vote = CommentVote.create! valid_attributes
      expect {
        delete comment_vote_url(comment_vote)
      }.to change(CommentVote, :count).by(-1)
    end

    it "redirects to the comment_votes list" do
      comment_vote = CommentVote.create! valid_attributes
      delete comment_vote_url(comment_vote)
      expect(response).to redirect_to(comment_votes_url)
    end
  end
end
