require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/subreddits', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Subreddit. As you add validations to Subreddit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /subreddit_posts' do
    it 'renders a successful response' do
      Subreddit.create! valid_attributes
      get subreddits_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      subreddit = Subreddit.create! valid_attributes
      get subreddit_url(subreddit)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_subreddit_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      subreddit = Subreddit.create! valid_attributes
      get edit_subreddit_url(subreddit)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Subreddit' do
        expect do
          post subreddits_url, params: { subreddit: valid_attributes }
        end.to change(Subreddit, :count).by(1)
      end

      it 'redirects to the created subreddit' do
        post subreddits_url, params: { subreddit: valid_attributes }
        expect(response).to redirect_to(subreddit_url(Subreddit.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Subreddit' do
        expect do
          post subreddits_url, params: { subreddit: invalid_attributes }
        end.to change(Subreddit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post subreddits_url, params: { subreddit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested subreddit' do
        subreddit = Subreddit.create! valid_attributes
        patch subreddit_url(subreddit), params: { subreddit: new_attributes }
        subreddit.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the subreddit' do
        subreddit = Subreddit.create! valid_attributes
        patch subreddit_url(subreddit), params: { subreddit: new_attributes }
        subreddit.reload
        expect(response).to redirect_to(subreddit_url(subreddit))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        subreddit = Subreddit.create! valid_attributes
        patch subreddit_url(subreddit), params: { subreddit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested subreddit' do
      subreddit = Subreddit.create! valid_attributes
      expect do
        delete subreddit_url(subreddit)
      end.to change(Subreddit, :count).by(-1)
    end

    it 'redirects to the subreddits list' do
      subreddit = Subreddit.create! valid_attributes
      delete subreddit_url(subreddit)
      expect(response).to redirect_to(subreddits_url)
    end
  end
end
