require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/user_subscriptions', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # UserSubscription. As you add validations to UserSubscription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      UserSubscription.create! valid_attributes
      get user_subscriptions_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      user_subscription = UserSubscription.create! valid_attributes
      get user_subscription_url(user_subscription)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_user_subscription_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      user_subscription = UserSubscription.create! valid_attributes
      get edit_user_subscription_url(user_subscription)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new UserSubscription' do
        expect do
          post user_subscriptions_url, params: { user_subscription: valid_attributes }
        end.to change(UserSubscription, :count).by(1)
      end

      it 'redirects to the created user_subscription' do
        post user_subscriptions_url, params: { user_subscription: valid_attributes }
        expect(response).to redirect_to(user_subscription_url(UserSubscription.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new UserSubscription' do
        expect do
          post user_subscriptions_url, params: { user_subscription: invalid_attributes }
        end.not_to change(UserSubscription, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_subscriptions_url, params: { user_subscription: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested user_subscription' do
        user_subscription = UserSubscription.create! valid_attributes
        patch user_subscription_url(user_subscription), params: { user_subscription: new_attributes }
        user_subscription.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the user_subscription' do
        user_subscription = UserSubscription.create! valid_attributes
        patch user_subscription_url(user_subscription), params: { user_subscription: new_attributes }
        user_subscription.reload
        expect(response).to redirect_to(user_subscription_url(user_subscription))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_subscription = UserSubscription.create! valid_attributes
        patch user_subscription_url(user_subscription), params: { user_subscription: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested user_subscription' do
      user_subscription = UserSubscription.create! valid_attributes
      expect do
        delete user_subscription_url(user_subscription)
      end.to change(UserSubscription, :count).by(-1)
    end

    it 'redirects to the user_subscriptions list' do
      user_subscription = UserSubscription.create! valid_attributes
      delete user_subscription_url(user_subscription)
      expect(response).to redirect_to(user_subscriptions_url)
    end
  end
end
